using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;

namespace Wireframe
{
    /// <summary>
    /// Creates a .cs file with Menu Items to assist the user in quickly uploading builds
    /// NOTE: Using this approach because I couldn't find a way to add them dynamically
    /// </summary>
    internal static class AutoGenerateMenuItems
    {
        /// <summary>
        /// Listens for when a code change
        /// TODO: I hope this doesn't cause a double compile...
        /// </summary>
        [InitializeOnLoadMethod]
        private static void InitializeOnLoadMethod()
        {
            if (Preferences.AutoGenerateMenuItems)
            {
                GenerateMenuItems(false);
            }
        }

        [MenuItem("Window/Build Uploader/Quick Upload/Generate Menu Items", false, 2000)]
        private static void GenerateMenuItems()
        {
            GenerateMenuItems(true);
        }
        
        private static void GenerateMenuItems(bool forceSave)
        {
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("namespace Wireframe");
            sb.AppendLine("{");
            sb.AppendLine("    /// This file is auto-generated by the Build Uploader package.");
            sb.AppendLine("    /// Do not modify this file directly as changes will be lost when it is regenerated.");
            sb.AppendLine("    public static class BuildUploader_AutoGeneratedMenuItems");
            sb.AppendLine("    {");

            List<UploadProfileSavedData> profiles = GetFiles();
            int totalDone = 0;
            
            HashSet<string> usedGUIDS = new HashSet<string>();
            for (var i = 0; i < profiles.Count; i++)
            {
                if (!usedGUIDS.Add(profiles[i].GUID))
                {
                    continue;
                }

                totalDone++;
                if (totalDone > 1)
                {
                    sb.AppendLine("");
                }
                
                var data = profiles[i];
                string menuitemName = $"Window/Build Uploader/Quick Upload/{totalDone}. {data.ProfileName}";
                sb.AppendLine($"        [UnityEditor.MenuItem(\"{menuitemName}\", false, 1000)]");
                sb.AppendLine($"        public static void BuildUploader_QuickUpload_{data.GUID}()");
                sb.AppendLine($"        {{");
                sb.AppendLine($"            AutoGenerateMenuItems.BeginUploadingProfile(\"{data.GUID}\", \"{data.ProfileName}\");");
                sb.AppendLine($"        }}");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            
            string libraryFolder = Path.Combine(Utils.s_packagePath, "Editor", "AutoGenerated");
            if (!Directory.Exists(libraryFolder))
            {
                Directory.CreateDirectory(libraryFolder);
            }
            
            
            string filePath = Path.Combine(libraryFolder, "AutoGeneratedMenuItems.cs");
            string newContent = sb.ToString();
            
            // Only write if content changed
            if (forceSave || !File.Exists(filePath) || File.ReadAllText(filePath) != newContent)
            {
                File.WriteAllText(filePath, newContent);
                AssetDatabase.ImportAsset(filePath);
            }
        }
        
        /// <summary>
        /// Called by auto-generated code
        /// </summary>
        /// <param name="guid"></param>
        /// <param name="profileName"></param>
        public static void BeginUploadingProfile(string guid, string profileName)
        {
            UploadProfileMeta metaData = new UploadProfileMeta();
            metaData.GUID = guid;
            metaData.ProfileName = profileName;
            QuickUploadPopup.ShowWindow(metaData);
        }

        private static List<UploadProfileSavedData> GetFiles()
        {
            List<UploadProfileSavedData> profiles = new List<UploadProfileSavedData>();
            string path = WindowUploadTab.UploadProfilePath;
            if (string.IsNullOrEmpty(path) || !Directory.Exists(path))
            {
                return profiles;
            }
            
            string[] files = Directory.GetFiles(path, "*.json");
            if (files.Length > 0)
            {
                for (int j = 0; j < files.Length; j++)
                {
                    string file = files[j];
                    string json = File.ReadAllText(file);
                    UploadProfileSavedData savedData;
                    try
                    {
                        savedData = UploadProfileSavedData.FromJSON(json);
                    }
                    catch (Exception)
                    {
                        continue;
                    }

                    if (savedData == null || string.IsNullOrEmpty(savedData.GUID))
                    {
                        continue;
                    }

                    profiles.Add(savedData);
                }

                if (profiles.Count > 0)
                {
                    profiles.Sort((a, b) =>
                    {
                        int compare = String.Compare(a.ProfileName, b.ProfileName, StringComparison.Ordinal);
                        if (compare == 0)
                        {
                            return String.Compare(a.GUID, b.GUID, StringComparison.Ordinal);
                        }

                        return compare;
                    });
                }
            }

            return profiles;
        }
    }
}